[project]
name = "tp-ultimate-edition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gclib[speedups]",
    "ninja>=1.13.0",
]

[tool.uv.sources]
gclib = { git = "https://github.com/LagoLunatic/gclib.git" }
